package ninja.egg82.core;

public class SQLExecuteResult {
    private final int recordsAffected;
    private final String[] autoGeneratedKeyColumns;
    private final Object[] autoGeneratedKeys;

    public SQLExecuteResult() {
        this.recordsAffected = -1;
        this.autoGeneratedKeyColumns = null;
        this.autoGeneratedKeys = null;
    }

    public SQLExecuteResult(int recordsAffected, String[] autoGeneratedKeyColumns, Object[] autoGeneratedKeys) {
        this.recordsAffected = recordsAffected;
        this.autoGeneratedKeyColumns = autoGeneratedKeyColumns;
        this.autoGeneratedKeys = autoGeneratedKeys;
    }

    public int getRecordsAffected() { return recordsAffected; }

    public String[] getAutoGeneratedKeyColumns() { return autoGeneratedKeyColumns; }

    public Object[] getAutoGeneratedKeys() { return autoGeneratedKeys; }
}
